In [1]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
#Getting and cleaning dataset

dataset = pd.read_csv('Downloads/pulsar_stars.csv')
dataset.dropna()
dataset.head()

Mean of the integrated profile  \
0                       140.562500   
1                       102.507812   
2                       103.015625   
3                       136.750000   
4                        88.726562   

    Standard deviation of the integrated profile  \
0                                      55.683782   
1                                      58.882430   
2                                      39.341649   
3                                      57.178449   
4                                      40.672225   

    Excess kurtosis of the integrated profile  \
0                                   -0.234571   
1                                    0.465318   
2                                    0.323328   
3                                   -0.068415   
4                                    0.600866   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.699648                   3.199833   
1                            -0.515088                   1.677258   
2                             1.051164                   3.121237   
3                            -0.636238                   3.642977   
4                             1.123492                   1.178930   

    Standard deviation of the DM-SNR curve  \
0                                19.110426   
1                                14.860146   
2                                21.744669   
3                                20.959280   
4                                11.468720   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                              7.975532                      74.242225   
1                             10.576487                     127.393580   
2                              7.735822                      63.171909   
3                              6.896499                      53.593661   
4                             14.269573                     252.567306   

   target_class  
0             0  
1             0  
2             0  
3             0  
4             0

In [3]:
# The total no of columns

dataset.columns

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve', ' Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [4]:
# Getting the X_data

X_data = dataset.iloc[:,0:-1].values
X_data[0:5]

array([[ 1.40562500e+02,  5.56837821e+01, -2.34571412e-01,
        -6.99648398e-01,  3.19983278e+00,  1.91104263e+01,
         7.97553179e+00,  7.42422249e+01],
       [ 1.02507812e+02,  5.88824300e+01,  4.65318154e-01,
        -5.15087909e-01,  1.67725752e+00,  1.48601457e+01,
         1.05764867e+01,  1.27393580e+02],
       [ 1.03015625e+02,  3.93416494e+01,  3.23328365e-01,
         1.05116443e+00,  3.12123746e+00,  2.17446687e+01,
         7.73582202e+00,  6.31719091e+01],
       [ 1.36750000e+02,  5.71784487e+01, -6.84146380e-02,
        -6.36238369e-01,  3.64297659e+00,  2.09592803e+01,
         6.89649891e+00,  5.35936607e+01],
       [ 8.87265625e+01,  4.06722254e+01,  6.00866079e-01,
         1.12349169e+00,  1.17892977e+00,  1.14687196e+01,
         1.42695728e+01,  2.52567306e+02]])

In [5]:
# Getting the Y_data

Y_data = dataset.iloc[:,-1].values
Y_data[0:5]

array([0, 0, 0, 0, 0])

In [6]:
# Scaling the X_data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [7]:
X_data = scaler.fit_transform(X_data)
X_data[0:5]

array([[ 1.14931702,  1.33483164, -0.66956953, -0.400459  , -0.31944026,
        -0.37062547, -0.07279778, -0.28743812],
       [-0.3341682 ,  1.80226533, -0.01178476, -0.37053549, -0.37110188,
        -0.5889241 ,  0.50442694,  0.21158145],
       [-0.31437216, -1.05332222, -0.14523256, -0.11659286, -0.32210703,
        -0.23532816, -0.12599609, -0.39137346],
       [ 1.0006944 ,  1.55325441, -0.51340862, -0.39017809, -0.3044042 ,
        -0.27566649, -0.31226539, -0.4813003 ],
       [-0.87140244, -0.85887881,  0.11560871, -0.10486616, -0.38801036,
        -0.76311112,  1.32402614,  1.38679399]])

In [8]:
#Splitting data into training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_data,Y_data)

In [16]:
# Importing libraries for ANN creation

from keras.models import Sequential
from keras.layers import Dense

In [10]:
#Building ANN

classifier = Sequential()
classifier.add(Dense(10 , input_dim = 8   , activation='relu'))
classifier.add(Dense(6  , input_dim = 8 , activation = 'relu'))
classifier.add(Dense(4  , input_dim = 6 , activation = 'relu'))
classifier.add(Dense(1  , input_dim = 4 , activation = 'relu'))
classifier.add(Dense(1  , activation = 'sigmoid'))

In [11]:
# Defining the loss and optimizer

classifier.compile(loss = 'binary_crossentropy' , optimizer='adam' , metrics = ['accuracy'])

In [12]:
# Fitting the data to model

classifier.fit(x_train,y_train,epochs = 200 , batch_size=100 )

Epoch 1/200
13423/13423 [==============================] - 2s 133us/step - loss: 0.4744 - acc: 0.9067
Epoch 2/200
13423/13423 [==============================] - 1s 56us/step - loss: 0.1739 - acc: 0.9067
Epoch 3/200
13423/13423 [==============================] - 1s 56us/step - loss: 0.1262 - acc: 0.9067
Epoch 4/200
13423/13423 [==============================] - 1s 57us/step - loss: 0.1192 - acc: 0.9067
Epoch 5/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.1162 - acc: 0.9067
Epoch 6/200
13423/13423 [==============================] - 1s 57us/step - loss: 0.1135 - acc: 0.9471
Epoch 7/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.1109 - acc: 0.9792
Epoch 8/200
13423/13423 [==============================] - 1s 55us/step - loss: 0.1083 - acc: 0.9795
Epoch 9/200
13423/13423 [==============================] - 1s 55us/step - loss: 0.1058 - acc: 0.9797
Epoch 10/200
13423/13423 [==============================] - 1s 56us/step - loss: 0.1032 - 

13423/13423 [==============================] - 1s 54us/step - loss: 0.0635 - acc: 0.9809
Epoch 82/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.0633 - acc: 0.9813
Epoch 83/200
13423/13423 [==============================] - 1s 53us/step - loss: 0.0632 - acc: 0.9813
Epoch 84/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.0632 - acc: 0.9811
Epoch 85/200
13423/13423 [==============================] - 1s 53us/step - loss: 0.0632 - acc: 0.9810
Epoch 86/200
13423/13423 [==============================] - 1s 53us/step - loss: 0.0632 - acc: 0.9811
Epoch 87/200
13423/13423 [==============================] - 1s 53us/step - loss: 0.0631 - acc: 0.9813
Epoch 88/200
13423/13423 [==============================] - 1s 52us/step - loss: 0.0632 - acc: 0.9810
Epoch 89/200
13423/13423 [==============================] - 1s 52us/step - loss: 0.0630 - acc: 0.9808
Epoch 90/200
13423/13423 [==============================] - 1s 53us/step - loss: 0.0630 - acc: 

13423/13423 [==============================] - 1s 66us/step - loss: 0.0615 - acc: 0.9814
Epoch 161/200
13423/13423 [==============================] - 1s 61us/step - loss: 0.0615 - acc: 0.9814
Epoch 162/200
13423/13423 [==============================] - 1s 70us/step - loss: 0.0611 - acc: 0.9811
Epoch 163/200
13423/13423 [==============================] - 1s 65us/step - loss: 0.0611 - acc: 0.9812
Epoch 164/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.0614 - acc: 0.9810
Epoch 165/200
13423/13423 [==============================] - 1s 54us/step - loss: 0.0612 - acc: 0.9810
Epoch 166/200
13423/13423 [==============================] - 1s 57us/step - loss: 0.0612 - acc: 0.9809
Epoch 167/200
13423/13423 [==============================] - 1s 63us/step - loss: 0.0611 - acc: 0.9813
Epoch 168/200
13423/13423 [==============================] - 1s 60us/step - loss: 0.0611 - acc: 0.9812
Epoch 169/200
13423/13423 [==============================] - 1s 67us/step - loss: 0.061

So here we get the accuracy score of 98% 

In [13]:
# Data for prediction

X_pred = np.array([dataset.iloc[1,:-1]])
print(X_pred)

[[102.5078125   58.88243001   0.46531815  -0.51508791   1.67725752
   14.86014572  10.57648674 127.3935796 ]]


In [14]:
# Prediciting

prediction = classifier.predict(X_pred)
print(prediction)

[[0.]]


In [15]:
# Getting accuracy score on testing data

classifier.evaluate(x_test,y_test)

4475/4475 [==============================] - 0s 110us/step


[0.07312661368337424, 0.9774301675977654]

this one is loss and , this is accuracy